openapi: 3.0.2
info:
  title: "tree API"
  version: "1.0.0"
  description: "OpenAPI specifications for a simple API that exposes a tree data-structure"
paths:
  /:
    parameters:
      - $ref: '#/components/parameters/treeQuery'

    get:
      operationId: get_tree
      description: "Retrieves information about the requested tree"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Tree'
              example:
                name: "Modeling Tree"
                root: "7865b1fa-e680-11e9-ba43-ac9e17b76a71"

        '400':
          description: "The request was not structured correctly (e.g. a required key was missing)."
   
  /nodes:
    get:
      operationId: get_nodes
      description: "Returns UUIDs for all the nodes in a tree (other than the root group)."
      parameters:
        - $ref: '#/components/parameters/treeQuery'
        - in: query
          name: limit
          description: "If provided, a positive integer value specifying the maximum number of UUID’s to return"
          schema:
            type: integer
            minimum: 0
        - in: query
          name: marker
          description: "If provided, a string value indicating that only UUID’s that occur after the marker value will be returned."
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    description: "Flat list of nodes in tree"
                    properties:
                      nodes:
                        type: array
                        items: 
                          type: string
                          format: uuid
              example:
                nodes:
                  - "d29dced4-4399-4bdc-951d-d474a48db477"
                  - "5e92f325-2085-45ab-9c21-8a9019a2290d"
                  - "17895910-9d97-45d0-aeeb-0faaff44080e"
                  - "e7c5e7f0-a1e3-4d2a-b958-494c33923fa0"
                  - "d3e0da1c-e7a4-4adb-960c-00b477cb1df5"

  /nodes/{node_id}:
    parameters:
      - $ref: '#/components/parameters/nodeId'
      - $ref: '#/components/parameters/treeQuery'

    get:
      operationId: get_node
      description: "Returns information about the node with the UUID given in the URI"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Node'
                  - type: object
                    properties:
                      children:
                        type: array
                        nullable: true
                        items:
                          $ref: '#/components/schemas/Node'
                      parent:
                        $ref: '#/components/schemas/Node'
              examples:
                Group1Node:
                  summary: "Example of a non-leaf"
                  value:
                    id: "17895910-9d97-45d0-aeeb-0faaff44080e"
                    name: "Group 1"
                    children:
                      - id: "e7c5e7f0-a1e3-4d2a-b958-494c33923fa0"
                        name: "Cylinder 1"
                        href: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0/nodes/e7c5e7f0-a1e3-4d2a-b958-494c33923fa0
                      - id: "d3e0da1c-e7a4-4adb-960c-00b477cb1df5"
                        name: "Sphere 1"
                        href: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0/nodes/d3e0da1c-e7a4-4adb-960c-00b477cb1df5
                    parent: 
                      id: "7865b1fa-e680-11e9-ba43-ac9e17b76a71"
                      name: "Model"
                      href: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0/nodes/7865b1fa-e680-11e9-ba43-ac9e17b76a71
                CylinderLeaf:
                  summary: "Example of cylinder leaf"
                  value:
                    id: "e7c5e7f0-a1e3-4d2a-b958-494c33923fa0"
                    name: "Cylinder 1"
                    href: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0/nodes/e7c5e7f0-a1e3-4d2a-b958-494c33923fa0
                    children: null
                    parent: 
                      id: "17895910-9d97-45d0-aeeb-0faaff44080e"
                      name: "Group1"
                      href: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0/nodes/17895910-9d97-45d0-aeeb-0faaff44080e
 
components:
  schemas:

    Tree:
      type: object
      properties:
        name:
          type: string
          description: "Name of the tree (defaults to root's name)"
        root:
          type: string
          description: "The UUID of the root node of this tree"

    Node:
      type: object
      nullable: true
      properties:
        id:
          description: "UUID of requested node"
          type: string
          format: uuid
        name:
          description: "User name of the node"
          type: string
        childrenCount:
          description: "Number of children"
          type: integer
          minimum: 0
        href:
          description: "link to node resource"
          type: string


    RelatedResources:
      type: object
      properties:
        hrefs:
          description: "List to related resources"
          # https://h5serv.readthedocs.io/en/latest/Hypermedia.html
          type: array
          items:
            type: object
            properties:
              rel:
                description: type of relation
                type: string
                enum: [attributes ,data ,database ,groupbase ,home ,owner ,root ,self, typebase]
              href:
                description: link
                type: string

  parameters:
      
    treeQuery:
      in: query
      description: "specifies tree if DNS server is not setup"
      name: host
      schema:
        type: string
        #TODO: format ?host=tall.public.data.hdfnode.org
    
    nodeId:
      in: path
      name: node_id
      description: "UUID of the node"
      required: true
      schema:
        type: string
        format: uuid


# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pcrespov/treeapi/1.0
